### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by B-Galati** [doctrine/doctrine-website#103]
Hello and thanks for this new website :+1: 

Would it be possible to add a RSS feed ?

**Comment by jwage** [comment]
Yes, it should be possible. Did we have one before? What was the url you were using if so?

**Comment by jwage** [comment]
I will add it at /atom.xml

**Comment by jwage** [comment]
Added it in #105 and is available here https://www.doctrine-project.org/atom.xml

**Comment by B-Galati** [comment]
That was quick! Thank you :-)

**Comment by agilare** [comment]
My feed reader (Thunderbird 60) cannot read https://www.doctrine-project.org/atom.xml because there is some errors : 

```
This feed does not validate.

    line 2, column 0: feed is in an invalid namespace: https://www.w3.org/2005/Atom [help]

        <feed xmlns="https://www.w3.org/2005/Atom">

    line 55, column 8: Missing entry element: author (10 occurrences) [help]

                </entry>
                ^

In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

    line 2, column 0: Use of unknown namespace: https://www.w3.org/2005/Atom [help]

        <feed xmlns="https://www.w3.org/2005/Atom">
```

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.doctrine-project.org%2Fatom.xml
