### ISSUE TITLE
Building the website does not work on windows

### ISSUE THREAD

**Issue by stof** [doctrine/doctrine-website#108]
While a nice-to-have, being unable to build the website on windows might make contributions harder for some people (and yes, I tried contributed from my Windows computer rather than the Ubuntu one I'm using for development most of the time).

Until now I identified these issues:

- sculpin has a bug on windows, breaking the CLI initialization (fixed in https://github.com/dflydev/dflydev-embedded-composer/pull/22)
- the `build-website` command fails when trying to run processes using globs with `mv`

**Comment by jwage** [comment]
@stof to be honest, I don't understand what the purpose of the embedded composer is. Can we eliminate it all together?

As for the build-website command, I was already thinking about migrating all the filesystem operations to Finder and Filesystem components. I think that would handle making sure it works on both windows and linux right?

**Comment by stof** [comment]
> git@github.com:stof/doctrine-website.git

yeah, probably.

> I don't understand what the purpose of the embedded composer is. Can we eliminate it all together?

embedded-composer is a dependency of sculpin, for its plugin management used when using Sculpin as a phar with composer-managed plugins (which is a [deprecated way](https://blog.sculpin.io/2016/08/31/deprecating-phar-distribution-and-embedded-composer/) to use Sculpin and not the one you use).
Note that the dev version of Sculpin 3.x s dropping this code entirely. But there is no way to skip it in 2.x AFAICT.

**Comment by jwage** [comment]
Understood. I will work on swapping out the operations with filesystem and then we can test again.

**Comment by jwage** [comment]
I'm also going to look at making a custom command to do the sculpin build so we can by pass the embedded composer.

**Comment by stof** [comment]
The embedded-composer fix has been merged upstream now.

**Comment by jwage** [comment]
Thanks. I started to get a windows VM setup so I can test my changes in #124. I will report back once I know more.

**Comment by Majkl578** [comment]
@jwage Maybe add AppVeyor builds here?

**Comment by SenseException** [comment]
Look like was fixed with #139.
