### ISSUE TITLE
Add a place that documents and standardizes our policies for releases, BC, depreciation, etc.

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#111]
- Release cycle
  - Every month we have a bug fix release.
  - Every 6 months we have a minor release.
  - Every 2 years we have a major release.
- Only maintain at most 3 branches at a time per project.
  - 1 branch for current stable release 
  - 1 branch for previous stable release
  - 1 branch for master (next)
- All bug fixes should be targeted to the master branch and then cherry-picked to each branch where the bug fix applies.
  - We need some kind of tooling to automate this and ensure that all applicable bugs are cherry-picked to each branch where relevant.
- New features are merged in to the master branch.
- Trigger deprecations warnings at runtime whenever possible before the BC break is released.

**Comment by ostrolucky** [comment]
Target branch for bug fixes contradicts https://github.com/doctrine/doctrine2/blob/master/CONTRIBUTING.md Also rebase strategy clearly in use is not mentioned.

@Majkl578 @guilhermeblanco can you correct this please?

**Comment by Majkl578** [comment]
@ostrolucky That's intentional (see https://github.com/doctrine/doctrine2/pull/7107), ORM has non-standard workflow right now by design.

**Comment by jwage** [comment]
I setup a new section on the website where we can start to publish these policies https://www.doctrine-project.org/policies.html
