### ISSUE TITLE
Use travis ci to do deploys

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#12]
Right now we are using a vm in AWS to do the builds but it would be ideal if we could use 100% travis. Someone needs to figure out how to make this work with our setup.

**Comment by stof** [comment]
the hard thing about it is that the website does not depend only on content in this repo, as the docs are in each project. Using the CI of this repo to build the doc would probably imply making an update in this repo any time a doc is updated in the other repos too.
How do you see this working ?

**Comment by jwage** [comment]
You are right, I don't think it would work for changes to the docs repos. I'm not sure how it could work right now.
