### ISSUE TITLE
Cookbook links broken

### ISSUE THREAD

**Issue by deltab** [doctrine/doctrine-website#130]
Some non-API documentation pages are also missing, e.g.
* https://www.doctrine-project.org/projects/doctrine-orm/en/stable/cookbook/implementing-wakeup-or-clone.html
* http://doctrine-orm.readthedocs.io/en/latest/cookbook/implementing-wakeup-or-clone.html

**Comment by jwage** [comment]
I added `stable` as an alias for the current stable version in #133.

**Comment by deltab** [comment]
Thanks! The first link is working now. Would adding `latest` as an alias fix the second link?

**Comment by jwage** [comment]
No, the 2nd link is on readthedocs.io domain which we have no control over. We are going to be shutting down the readthedocs.io and we should be going through doctrine-project.org going forward.
