### ISSUE TITLE
Backslashes before underscores in headings

### ISSUE THREAD

**Issue by deltab** [doctrine/doctrine-website#131]
In https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2.x/cookbook/implementing-wakeup-or-clone.html headings have backslashes before underscores, e.g. `Safely implementing \_\_wakeup`.

**Comment by jwage** [comment]
Looks like it is in the source for some reason https://github.com/doctrine/mongodb-odm/edit/1.2.x/docs/en/cookbook/implementing-wakeup-or-clone.rst

**Comment by malarzm** [comment]
Most probably it was escaping, on RTD it's rendered correctly: http://doctrine-orm.readthedocs.io/projects/doctrine-mongodb-odm/en/1.2.x/cookbook/implementing-wakeup-or-clone.html

**Comment by SenseException** [comment]
Looks fixed for at least the supported versions.
