### ISSUE TITLE
Limit main content width

### ISSUE THREAD

**Issue by garak** [doctrine/doctrine-website#135]
Internal pages (e.g. https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/index.html) are composed by a sidebar and a main content area that is currently getting all the remaining space of the viewport (see attached screenshot).
I think that such width should be limited, since on large screen it's hard to read

![doctrine](https://user-images.githubusercontent.com/179866/39052714-3acf76da-44ad-11e8-8d9d-00e535e326eb.png)

**Comment by jwage** [comment]
Thanks. I agree. I need to figure out how to do this. This is pushing up against the boundaries of my css skills but I will try to work on something to make it better :)
