### ISSUE TITLE
Add 'contribute on github link' to each page

### ISSUE THREAD

**Issue by matthewtrask** [doctrine/doctrine-website#136]
Was looking at a page and noticed a few small things that could be fixed, but no quick link to the repo.

Will add this over the weekend I think, should not be terribly difficult.

**Comment by jwage** [comment]
I don't see a way to get at the path to the source file that generates the html file in sculpin so I think in each source sculpin file we will just have to add the path to the file. So for example in https://github.com/doctrine/doctrine-website/blob/master/source/community.html you would add a parameter at the top like this:

```
---
layout: default
title: Community
menuSlug: community
editPath: /source/community.html
---
```

And then in the twig templates in `source/_layouts/layout.html` to add the Edit link you can do something like:

{% if page.editPath is defined and page.editPath %}
     <a href="https://github.com/doctrine/doctrine-website/edit/master{{ page.editPath }}">Edit</a>
{% endif %}
