### ISSUE TITLE
Missing integrity + crossorigin for some subresources

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine-website#151]
There are some CSS/JS linked with integrity and crossorigin attributes already, but some are missing them. :|

https://caniuse.com/#feat=subresource-integrity

**Comment by jwage** [comment]
I can fix this. How can I generate the integrity value for a file in PHP? Can I do it natively or pipe to command line?

**Comment by Majkl578** [comment]
Basically:
```php
'sha384-' . base64_encode(hash('sha384', file_get_contents('https://example.com/some.js'), true));
```
Even easier for local CSS.
Just make sure (in case of CDNs) you use versioned URLs otherwise if the script changes, JS breaks (that's the point of the integrity check though).

Either way, external links should imho be done manually, otherwise you can serve already malicious JS/CSS.
