### ISSUE TITLE
Document how to do releases

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#152]
- how to format tags
- semver info
- how to generate change log giving thanks to each contributor
- create tooling to automate pieces of the process? Do we need anything?

**Comment by jwage** [comment]
@Ocramius I think you said you were working on this. Anything I can do to help?

**Comment by Ocramius** [comment]
I just need to pick it up again - being extremely lazy these days. Added it
to my calendar to do something about it before EOD today.

**Comment by Ocramius** [comment]
FWIW, the WIP PR for this is at https://github.com/doctrine/doctrine-website/pull/262

Closing here, let's continue there.
