### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by garak** [doctrine/doctrine-website#164]
Just discovered on [SO](https://stackoverflow.com/questions/5988636/doctrine-2-how-to-use-discriminator-column-in-where-clause/5992273#5992273) a broken link. I think a redirect is missing.

**old link**: https://www.doctrine-project.org/docs/orm/2.0/en/reference/dql-doctrine-query-language.html
**new link**: https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html

**Comment by jwage** [comment]
Unfortunately we do not have an easy way to fix this. The old link is a really old link that used to redirect to readthedocs, and we have no way to setup redirects on readthedocs.
