### ISSUE TITLE
Dead links found on website

### ISSUE THREAD

**Issue by SenseException** [doctrine/doctrine-website#166]
By using wget as a spider, I checked the website for 404 / errors and retrieved the following list:

[wget.log.gz](https://github.com/doctrine/doctrine-website/files/1973796/wget.log.gz)

At the end of the list are 305 broken links listed. Most of them are from templates using a placeholder {{url}}, which may not be usable by wget, but this needs to be confirmed first.

The used wget command to create the log-file:

`wget --spider -r -nd -nv -l 10 -w 2 -o wget.log  https://www.doctrine-project.org`

I used 10 levels `-l` for my check, which made wget run ~8 hours and a waiting time `-w` of two seconds between the downloads for the web server. A higher level may show more broken links.

Related issues:

- #164

**Comment by SenseException** [comment]
Some external links used in the documentation aren't 404, but lead to deprecated or outdated content. These links aren't listed in the url-list.

**Comment by deltab** [comment]
What about broken links found elsewhere? e.g. https://doctrine-orm.readthedocs.io/en/latest/reference/annotations-reference.html from search engine results.

**Comment by SenseException** [comment]
https://doctrine-orm.readthedocs.io isn't in use anymore. Please use https://www.doctrine-project.org for all the Doctrine projects.

**Comment by vladyslavstartsev** [comment]
I've found that there are a lot of broken links due to jira

something like this
http://www.doctrine-project.org/jira/browse/DCOM-129

what I can try to do is to find a link like the above one and change it to https://github.com/doctrine/common/issues/428

is that a good idea? should I try?

**Comment by jwage** [comment]
Yes, we would accept PRs to docs to update links :+1:

**Comment by SenseException** [comment]
@vladyslavstartsev The PR doctrine/orm#7385 covers fixes for links of doctrine/orm, but I haven't checked the other projects yet.

**Comment by Ocramius** [comment]
Is there a grep syntax that worked for you here? Error messages seem to be on a new line each...

**Comment by SenseException** [comment]
No, it was just the command above. After some links were fixed since the creation of the log, we can consider another scan with a different tool.

**Comment by vladyslavstartsev** [comment]
I used level 20
`wget --spider -r -nd -nv -l 20 -w 2 -o wget.log https://www.doctrine-project.org`
[wgetlog.tar.gz](https://github.com/doctrine/doctrine-website/files/2872915/wgetlog.tar.gz)

**Comment by SenseException** [comment]
If there aren't any further fixes done, I assume that most links were fixed. I'll close this issue in favor of new ones that can name and show new dead links that will pop up over time.
