### ISSUE TITLE
Bidirectional one-to-one association mapping doesn't say that a unique key is going to be created.

### ISSUE THREAD

**Issue by d-ph** [doctrine/doctrine-website#169]
Hello,

The `Generated MySQL Schema` section of [One-To-One, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-bidirectional) doesn't say that a unique key will be created on the owning side's column. This is inconsistent with the docs for [One-To-One, Unidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-unidirectional), which do mention the unique key.

Thanks.

**Comment by SenseException** [comment]
Hi, when I create a bi-directional

**Comment by SenseException** [comment]
Hi, when I create a bidirectional relation between entities, I don't get a unique key. It's behaves like in the documention.

Which database did you use for getting a unique key? And which ORM version?

**Comment by d-ph** [comment]
Hi,

I use Postgres 9.6.8 and `doctrine/orm` 2.6.1 (I've just upgraded to latest stable to see whether it changes anything).

I essentially took the Consumer and Cart example:
```php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Traits\EntityIdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="cart")
 */
class Cart
{
    use EntityIdTrait;

    // ...

    /**
     * One Cart has One Customer.
     * @ORM\OneToOne(targetEntity="Customer", inversedBy="cart")
     */
    private $customer;

    // ...
}
```
```php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Traits\EntityIdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="customer")
 */
class Customer
{
    use EntityIdTrait;

    // ...

    /**
     * One Customer has One Cart.
     * @ORM\OneToOne(targetEntity="Cart", mappedBy="customer")
     */
    private $cart;

    // ...
}
```
And run `./bin/console doctrine:schema:update --dump-sql`, which produces:
```sql
     CREATE TABLE customer (id SERIAL NOT NULL, PRIMARY KEY(id));
     CREATE TABLE cart (id SERIAL NOT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY(id));
     CREATE UNIQUE INDEX UNIQ_BA388B79395C3F3 ON cart (customer_id);
     ALTER TABLE cart ADD CONSTRAINT FK_BA388B79395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
```
If you ask me, it makes sense to have the UNIQUE key on the `cart(customer_id)`, since this is a one-to-one relation, so no other `Cart` should have the same `Consumer` assigned.

**Comment by Ocramius** [comment]
Yes, it is correct that the owning side of the association has a `UNIQUE` constraint. What action is to be taken for this issue?

**Comment by SenseException** [comment]
I suggest two actions:

* Update ORM repository with a PR to have an unique constraint for every supported database (if unique is supported) on One-To-One bidirectional
* Replace the resulting SQL output in the documentation with a description and/or diagram of the resulting changes. It looks like that the documentation currently shows MySQL queries as output.

**Comment by cybernet** [comment]
still open :)

**Comment by SenseException** [comment]
@cybernet You're welcome to create a PR if you like. :-)

**Comment by SenseException** [comment]
This was rather ORM related than website related. Issues for each project's docs have to be created in the respective repositories.
