### ISSUE TITLE
Run phpcs against codebase

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#179]
I never followed up and did this. Run phpcs and phpstan level 7 against codebase. Fix all the errors and add checks to travis build.

**Comment by SenseException** [comment]
How to handle smells of inherited methods, that has to be compatible with the parent class? Disabling for the affected line?

**Comment by Majkl578** [comment]
@SenseException By using `@phpcsSuppress`, like here:
https://github.com/slevomat/coding-standard/blob/d43b9a627cdcb7ce837a1d85a79b52645cdf44bc/SlevomatCodingStandard/Sniffs/PHP/TypeCastSniff.php#L37

**Comment by SenseException** [comment]
My question was about if we should do this.
In https://github.com/doctrine/doctrine-website/pull/177#discussion_r195926852 I asked about adapting a forked repo. I'm not sure if this will only be needed in a *gregwar/rst* fork. If there's a third party library which is not in our hand, we still have the option of disabling affected smells or lines. I want to prevent such suppressing annotations as much as possible.

**Comment by jwage** [comment]
I will hopefully be able to fixup the RST parser pretty quickly so it won't be an issue for long.

**Comment by jwage** [comment]
https://github.com/doctrine/rst-parser exists now and it has Doctrine CS 4.0 applied and PHPStan Level 7. I updated doctrine website source and we now have CS and phpstan level 7 here too.
