### ISSUE TITLE
Phase out doctrine-*.readthedocs.io

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine-website#184]
* https://doctrine-orm.readthedocs.io/en/latest/
* https://doctrine-dbal.readthedocs.io/en/latest/
* https://doctrine-common.readthedocs.io/en/latest/

These legacy docs need to be dropped, it's currently only a source of confusion as the content is outdated and not versioned.

Proposal: Redirect the main chapters to their counteparts on our new website, redirect the remainder to the project homepage.

**Comment by jwage** [comment]
These old doc links have been shutdown.
