### ISSUE TITLE
Performance Recommendation Contains Dead Link

### ISSUE THREAD

**Issue by kiler129** [doctrine/doctrine-website#185]
The page at https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/improving-performance.html links to itself under "See Doctrine Query Language chapter". It should link to https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/dql-doctrine-query-language.html#temporarily-change-fetch-mode-in-dql instead.

 //I will add PR later today.

**Comment by jwage** [comment]
Thanks. Closing this issue here. You can open a new issue or pull request on https://github.com/doctrine/doctrine2 where that code exists in https://github.com/doctrine/doctrine2/tree/master/docs
