### ISSUE TITLE
Search weirdly broken (at least in Safari)

### ISSUE THREAD

**Issue by ondrejmirtes** [doctrine/doctrine-website#190]
Hi,
I'm trying to search on the Doctrine website (https://www.doctrine-project.org) for string `matching`. It behaves in a weird way:

1) I can't scroll the results. In scrolls the background instead.
2) When I defocus the input, the search results disappear.

I have Safari 11.1.2 on macOS 10.13.6.

**Comment by ondrejmirtes** [comment]
BTW it does the same thing in Chrome.

**Comment by SenseException** [comment]
Having the result of the search as sticky as the navigation makes the search hard to use, even on mobiles. We could move the result container out of the `nav` tag as a quick win, but I'm not sure if this would still be a good markup.

**Comment by jwage** [comment]
Thanks to @SenseException for making a change that improves this. It is still not "great", but it is better.
