### ISSUE TITLE
Wrong link target to expressions page

### ISSUE THREAD

**Issue by ondrejmirtes** [doctrine/doctrine-website#191]
Hi,
I'm here https://www.doctrine-project.org/projects/doctrine-collections/en/latest/index.html and I'm trying to click on `You can read more about expressions >here<.` below the `matching` method description. Nothing happens.

I'm on Safari 11.1.2 on macOS 10.13.6.

**Comment by Ocramius** [comment]
Can this be reproduced in a "contemporary" browser? :D

**Comment by ondrejmirtes** [comment]
Yeah, it does the same thing in Chrome :P

**Comment by Ocramius** [comment]
Thanks :+1:

**Comment by SenseException** [comment]
Because the part of the `matching()` method had to be fixed anyway, I also did a fix for the link in PR doctrine/collections#158.

**Comment by SenseException** [comment]
The changes got merged and the link now references to the Expressions page. Thank you for reporting this.
