### ISSUE TITLE
CouchDB client project is missing from project page

### ISSUE THREAD

**Issue by j13k** [doctrine/doctrine-website#193]
There isn't much activity on the Doctrine CouchDB _Client_ project (https://github.com/doctrine/couchdb-client), however it would be good to provide a reference to it on the website [Projects](https://www.doctrine-project.org/projects.html) page.

**Comment by SenseException** [comment]
A simple documentation for starters in the doctrine/couchdb-client repository would be a nice to have. We could add this into the website and extend it later.

Would you like to create a PR in doctrine/couchdb-client? It needs to be written in reStructuredText and are put into /docs/en directory for english version.

You can take a look how it's done in dbal:
https://github.com/doctrine/dbal/tree/master/docs/en

**Comment by jwage** [comment]
I added doctrine/couchdb-client to the website as an inactive project. I only converted the README for the docs so if someone else wants to jump in and help revive this project, feel free. Thanks!
