### ISSUE TITLE
Show warning badge when browsing outdated docs

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine-website#197]
[Dismissible alert](https://getbootstrap.com/docs/4.1/components/alerts/#dismissing) would probably be enough.

**Comment by SenseException** [comment]
Everything that's not the latest version? Or do we have a common Doctrine rule when a version is "outdated"?

**Comment by Majkl578** [comment]
Those with `maintained: false` in projects.yaml. PR incoming. :)
