### ISSUE TITLE
Add documentation for doctrine/annotations

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#20]
Right now it is empty and says coming soon. Even something very basic to get started would be better than what we have now.

https://github.com/doctrine/annotations/tree/master/docs/en

**Comment by SenseException** [comment]
I'll take this one.

**Comment by jwage** [comment]
@SenseException awesome!

**Comment by jwage** [comment]
This is live now https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/index.html
