### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by simPod** [doctrine/doctrine-website#202]
Hey, just noticed syntax highlighting for website is not working

![image](https://user-images.githubusercontent.com/327717/44147337-fd093104-a093-11e8-82aa-915762bdbdef.png)

https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/transactions.html

**Comment by Majkl578** [comment]
Not really broken: the code block is not marked as a PHP block so it's just a generic block of code.

**Comment by simPod** [comment]
My laptop battery have just been depleted so I haven't really inspected it much. It might definitely be the case ;)
