### ISSUE TITLE
The Doctrine logo is far too big

### ISSUE THREAD

**Issue by samuelwilliams** [doctrine/doctrine-website#229]
The Doctrine logo is far too big, it currently takes up about half the view (see below). I suggest reducing the size of the logo to about 60px for all pages other than the homepage.

![untitled](https://user-images.githubusercontent.com/806430/44983803-96326480-af8b-11e8-88c4-71caaf01990a.png)

**Comment by Majkl578** [comment]
This is because CSS is not loaded properly (ctrl+f5 will fix it), but I have no idea why it happens, probably old version cached by your browser.
@jwage Possibly related to the disabled minification + added integrity checks.

**Comment by jwage** [comment]
It could be. I will deploy a new version that busts the cache.

**Comment by jwage** [comment]
This should be fixed.
