### ISSUE TITLE
Add documentation for doctrine/orientdb-odm

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#25]
Right now it is empty and says coming soon. Even something very basic to get started would be better than what we have now.

https://github.com/doctrine/orientdb-odm/tree/master/docs/en

**Comment by jwage** [comment]
@odino Is this something you'd be up for doing?

**Comment by odino** [comment]
hey @jwage :) it's been a while I've had a look at the orientdb odm, and honestly don't have time to add docs. Not sure if anyone from the community is interested as I think the project lost momentum :-P
