### ISSUE TITLE
Cleanup style.css

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#253]
https://github.com/doctrine/doctrine-website/blob/master/source/css/style.css

This file is a disaster. It could be cleaned up. Maybe adopt sass and/or tailwindcss.

**Comment by BhautikChudasama** [comment]
Do you need to convert it to scss?

**Comment by jwage** [comment]
Yes, that could be a good first step. We'd need to create a build process too.

**Comment by mmollick** [comment]
Looks like the previous PR's stalled out and never implemented the build step. I'd be happy to implement a build step and pre-commit linting for the styles. 
Are there any preferences on the tools used to accomplish this (e.g. Webpack vs Gulp)? 
While were at should we also add a build step to concat & minify the Javascript as well (Webpack makes this simple)?

**Comment by SenseException** [comment]
My personal choice would be Webpack. This might be useful for changes of the website's Javascript and JS libraries for bundling.
