### ISSUE TITLE
Mapping Matrix rendering is broken

### ISSUE THREAD

**Issue by afoeder** [doctrine/doctrine-website#268]
The [Mapping Matrix](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/types.html#mapping-matrix) currently looks like this:

![image](https://user-images.githubusercontent.com/1125168/48255320-a98b0180-e40c-11e8-9a86-3e356b1b945f.png)

I can try to look at it and follow-up with a PR if desired.

**Comment by SenseException** [comment]
Thank you for taking your time to report this issue :+1:. We are aware of this and there is already an issue in doctrine/rst-parser#38 in the RST repository. It will be handled there.
