### ISSUE TITLE
Sami is unmaintained - what to use instead?

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine-website#288]
Sami has been abandoned and is currently unmaintained: https://github.com/FriendsOfPHP/Sami/commit/394f3e156e814d362b88fa2f682fb8f5c273c970

We should look for a replacement or abandon hosting API docs entirely.

**Comment by malarzm** [comment]
I'd be ok with dropping API docs entirely, can't really recall when was last time I've preferred them over reading docs in the source code

**Comment by jwage** [comment]
I was planning on dropping api docs.
