### ISSUE TITLE
Contributor and Maintainer Count is 0

### ISSUE THREAD

**Issue by nicam** [doctrine/doctrine-website#289]
Hello there,

I just noticed that the contributer and maintainer counts are 0 on the Website. See the screenshots:

![Screenshot 2019-03-30 09 50 52](https://user-images.githubusercontent.com/182071/55275181-bd170600-52e2-11e9-9d7a-ea5caf651aea.png)
![Screenshot 2019-03-30 11 55 57](https://user-images.githubusercontent.com/182071/55275189-cacc8b80-52e2-11e9-8114-1f02629a255f.png)

cheers,

Pascal

**Comment by jwage** [comment]
Thanks. We have some issue where the api calls to github don't work and I haven't been able to reproduce it.

**Comment by jwage** [comment]
This is fixed now.
