### ISSUE TITLE
Audit all seo meta tags

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#307]
They are inconsistent and not complete on some pages. This data is also what shows for a url when you tweet a url or embed a link in slack, etc. So it is important that it is complete.

**Comment by SenseException** [comment]
Some `og:*` and maybe `twitter:*` meta tags should be added too. Should some of the documentation content become part of the description of each documentation site?

**Comment by jwage** [comment]
We have the og and twitter tagshttps://github.com/doctrine/doctrine-website/blob/master/templates/layouts/layout.html.twig#L57 

Fb and Twitter use the meta tags too so by cleaning up that it will improve there too.
