### ISSUE TITLE
Link to Slack invite is outdated

### ISSUE THREAD

**Issue by rbairwell** [doctrine/doctrine-website#324]
On https://www.doctrine-project.org/community/  under the heading of "Slack" it links to https://www.doctrine-project.org/slack which then redirects to https://doctrine.slack.com/join/shared_invite/enQtNjE5NDU1MTIyMzU5LTY2Mjk5NDlhODEzZDRhYmY5ZjNjODRhNTdiOGI1ZGMzNDQwOTk0YzA1OGNkOWRlZjIyZjdkYTNkYmQ4N2RmMTY - however  Slack reports "This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available."

Could the redirect be updated or the link to Slack removed?

**Comment by SenseException** [comment]
Seems like https://www.doctrine-project.org/slack was already fixed or it was just a small inconvenience. Thank you for reporting it. :+1:

**Comment by VladyslavChernyshov** [comment]
> Seems like https://www.doctrine-project.org/slack was already fixed or it was just a small inconvenience. Thank you for reporting it. 👍

It is outdated again.
