### ISSUE TITLE
Unreadable code colour on green background

### ISSUE THREAD

**Issue by malarzm** [doctrine/doctrine-website#327]
The note under first code example of https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#filtering-collections has green background and unreadable pink-ish `Group#getTodaysBirthdayUsers()` on it - I think the code text should have different color as it's barely readable (on my screen at list)

**Comment by stof** [comment]
As this pink color is the color used everywhere, maybe the solution would be to avoid using a green background for such tips. Maybe a bordered box could be enough.

Alternatively, maybe code spans should not be pink.
