### ISSUE TITLE
caution is not clear

### ISSUE THREAD

**Issue by vladyslavstartsev** [doctrine/doctrine-website#334]
On https://www.doctrine-project.org/contribute/index.html page it is said that

> Please note that once you have pushed your branch remotely you MUST NOT rebase!

but I haven't found info, why I must not rebase.
Also, there is no mentions on the cases like this
1) create branch
2) do work
3) `rebase` (this is ok, right?)
4) push and open PR
5) review started, fixes required
6) commit something
7) everything is ok with PR, but there is merge conflicts,
8) `pull --rebase` with the branch I opened PR to
9) can't push since this caution

It's really not clear how to do things, at least for me. 
If we can discuss more clear instruction it will be awesome.

**Comment by malarzm** [comment]
Indeed the "must not rebase" part makes absolutely no sense, rebasing is a pretty common thing we ask contributors to do. @greg0ire IIRC you've compiled a list of responses with tips how to proceed with git, would you mind taking a look what can we improve here? Or maybe entire page needs an overhaul

**Comment by greg0ire** [comment]
I will take a look 👍
