### ISSUE TITLE
Navbar glitchy when expanding in a certain viewport size

### ISSUE THREAD

**Issue by o-alquimista** [doctrine/doctrine-website#337]
See it yourself:
![Peek 19-02-2020 15-28](https://user-images.githubusercontent.com/25424263/74863355-8730a500-532c-11ea-9556-d0f78c200ca5.gif)

This only happens at a specific viewport size.

To reproduce:
- Start from a very small window size and slowly increase its width until the navigation sidebar appears to the left. That's probably the `md` breakpoint.
- Click the hamburguer menu icon to expand the collapsible navbar.

My browser is Firefox 73. Ubuntu 19.10 with GNOME on Xorg session.

**Comment by SenseException** [comment]
It is also reproducible in Chrome.
