### ISSUE TITLE
Extra white gap on right side in mobile view

### ISSUE THREAD

**Issue by pushpak1300** [doctrine/doctrine-website#341]
on domain
 https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/configuration.html#configuration
 extra white gap on right-side of screen in mobile view.
![Screenshot (92)](https://user-images.githubusercontent.com/31663512/66712954-08e25600-edc2-11e9-84d3-524bd025ffdf.png)

**Comment by pushpak1300** [comment]
Can anyone assign this issue to me?

**Comment by SenseException** [comment]
@pushpak1300 Do you like to create a PR for this issue because you want it to be assigned to you?

**Comment by pushpak1300** [comment]
Yes, @SenseException I will create PR for the issue.
