### ISSUE TITLE
"Deliberate git" link goes to 404 page

### ISSUE THREAD

**Issue by greeflas** [doctrine/doctrine-website#354]
Hi!
I have just read [Contribute docs](https://www.doctrine-project.org/contribute/index.html) and found that "Deliberate git" link goes to 404 page.
Maybe you have some mirror link to update this doc?

**Comment by SenseException** [comment]
Seems like the the path of the target page got renamed. A short search shows it's now https://www.rakeroutes.com/deliberate-git.

Thank you for reporting.

**Comment by greeflas** [comment]
You are welcome.
