### ISSUE TITLE
Web site build error In ProjectDataBuilder.php line 204: Notice: Undefined index: branchName

### ISSUE THREAD

**Issue by mdogancay** [doctrine/doctrine-website#378]
I'm trying to build a local copy of your web site using your contribution guide in your web site.
I made the necessary configuration settings. On the build web site data step i got an error :
```
In ProjectDataBuilder.php line 204:
  Notice: Undefined index: branchName 
```
[error output](https://ibb.co/0yBVLk5)
How can i fix this?

**Comment by SenseException** [comment]
Could be related to #372. I see notices in the daily GitHub Actions build with the same message.

There are also some repositories that are currently a work in progress where branches get renamed or deleted without adapting the website config in each repository. This is why there can be problems with the website build at the moment.

**Comment by mdogancay** [comment]
This PR must be manualy marged. Because i had to block ProcessFailedException in the /lib/ProcessFactory.php#run() function. Otherwise there is some other problems blocking the build process. With this PR, problems on this issue gain some flexibility. I made some comments on the code. U can see.

Thanks.
