### ISSUE TITLE
Search Results always empty

### ISSUE THREAD

**Issue by frost-byte** [doctrine/doctrine-website#390]
I am no longer able to see any live search results (my browser is scrolled to the top of the page)
It doesn't matter what I enter as a search term.

I'm using Google Chrome (Version 88.0.4324.150 (Official Build) (64-bit)) on Windows 10.
I just tried Firefox (v86.0 (64-bit)) and had the same issue.

![image](https://user-images.githubusercontent.com/852776/109563771-38285e80-7aae-11eb-965e-7909876cd46d.png)

**Comment by SenseException** [comment]
Thanks for opening this issue. Looks like this is still happening, depending on the version of the project. Some versions of a library still work.

**Comment by SenseException** [comment]
I had to create the search-index manually for the DBAL and ORM projects. It should work again for the specific versions. Please take a look.

On an unrelated side note: The search-index creation for at least one project doc broke. I'll see if I can fix that. I'll also see if I can improve the search-index build for the regular build process of the website.

**Comment by SenseException** [comment]
Seems like we reached our quota for the search engine and we have now no results at all. #392 needs to get a more sophisticated handling of a search-index build.
