### ISSUE TITLE
Documentation Search is Broken

### ISSUE THREAD

**Issue by LeoAdamek** [doctrine/doctrine-website#395]
Search within the [project's documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/index.html) does not work. Attempting to search the documentation causes an error with the following message:

> Operations quota exceeded. Change plan to get more Operations.

Due to this the documentation cannot be searched.

**Comment by greg0ire** [comment]
Maybe we should file for an Algolia for Open Source plan at https://www.algolia.com/for-open-source/ if not already done.

**Comment by SenseException** [comment]
See https://github.com/doctrine/doctrine-website/issues/390#issuecomment-792080951 for more info.
