### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by delasallejean** [doctrine/doctrine-website#408]
The CPU usage is high even when idle, between 15 and 30% on my laptop.

The source seem to be a loader (a SVG with a css animation) injected by the google translate javascript.
The animation triggers repaint events every second or so.

The repaint events can be seen using the profiler (just let it run 5 seconds without doing anything) and the following snippet to find the source:

```
window.onanimationiteration = console.log;
```

The real issue is on google side - why keep an animated spinner forever ? It doesn't even seem to be displayed on the page - but I can't find where such issues must be filed.

Also:
Setting display: none on the container of the animation stop the repaint events in Chrome.

![Screenshot from 2021-07-21 13-59-37](https://user-images.githubusercontent.com/3700200/126485217-cc871214-4bdf-4e2c-9c1d-d63056ea0f53.png)

![Screenshot from 2021-07-21 13-57-16](https://user-images.githubusercontent.com/3700200/126485224-c211d6f6-d4a4-4e54-83b7-ffd502d865d7.png)

![Screenshot from 2021-07-21 13-50-15](https://user-images.githubusercontent.com/3700200/126485235-43afd1e3-e78c-42cb-b663-16d108f136d4.png)

**Comment by mpdude** [comment]
Is it coming from the Google translation thing? 

If so, #422 suggests to remove that anyways.
