### ISSUE TITLE
Suggestion: Remove Google translation bar

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/doctrine-website#422]
I'm suggesting to remove the Google translation bar that was introduced in https://github.com/doctrine/doctrine-website/pull/141

Why?
1. Since it's loaded with JavaScript, it's causing a so-called Cumulative Layout Shift (CLS, see https://web.dev/cls/): After everything is on screen, the translation bar appears, moving everything down.
2. In that toolbar I've clicked the "Deactivate for English" button *at least* ;-) 100 times, but it keeps reappearing every time...

**Comment by SenseException** [comment]
The bar was, as far as I remember, a quick win to provide docs in multiple languages. I don't know how heavily it's used by our visitors, so just removing them isn't an appropriate option. If there's a way how we can see if people are enabling translations?
