### ISSUE TITLE
Is there any way to drop the top post about ukraine help?

### ISSUE THREAD

**Issue by AntonUnger** [doctrine/doctrine-website#460]
The post "Ukraine needs your help now!", being very true, hinders a lot, especially on small screen devices. Perhaps, would be better to place it otherwhere.

**Comment by greg0ire** [comment]
Just tried because I was wondering why it would disappear on desktop and not on mobile, and that seems to be because it takes 2 lines of text on mobile. The first one is hidden as intended, but not the second one.

**Comment by AntonUnger** [comment]
Agreed.

**Comment by jorgesumle** [comment]
You can use uBlock Origin and add a custom filter, but I think the solution is to remove the propaganda → #486
