### ISSUE TITLE
Anchors missing on some pages

### ISSUE THREAD

**Issue by greg0ire** [doctrine/doctrine-website#483]
I wanted to easily copy a link to a title in a documentation page, such as https://www.doctrine-project.org/contribute/index.html#coding-standard-check, and couldn't find any, although such handy anchors are present for instance on https://www.doctrine-project.org/projects/doctrine-orm/en/stable/tutorials/pagination.html 

The code responsible for this seems to be here: https://github.com/doctrine/doctrine-website/blob/a009d284d1a4200a503a0f0bc31384f3905d0f36/lib/Docs/RST/RSTPostBuildProcessor.php#L141-L148

**Comment by SenseException** [comment]
Looks like the project docs are getting the anchor link while the website itself doesn't.

**Comment by jaapio** [comment]
I fixed this in #594 :-)

**Comment by jaapio** [comment]
This issue can be closed now?

**Comment by greg0ire** [comment]
Absolutely!
