### ISSUE TITLE
Safari: Code snippets weird behaviour 

### ISSUE THREAD

**Issue by henrikac** [doctrine/doctrine-website#552]
I have noticed that some pages displays code snippets on top of each other, e.g. on [One-To-One, Unidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/association-mapping.html#one-to-one-unidirectional) (see attached screenshot).

![Screenshot 2023-11-03 at 11 51 04](https://github.com/doctrine/doctrine-website/assets/18054250/95be0d8c-e104-497c-ae0c-1d08edc6d81e)

**Comment by SenseException** [comment]
Hi @henrikac, which version of Safari do you use? Does https://www.doctrine-project.org/projects.html show similar problems?

**Comment by SenseException** [comment]
A funny coincidence: I was working on some JavaScript of the website and commented out some code to see the impact of it. When I comment out [these LoC](https://github.com/doctrine/doctrine-website/blob/78e80b87b6136f0890ac5ba9265882f2eda612f9/source/js/main.js#L23-L56) then I get the same effect as in the screenshot. These parts of the code haven't changed for years while jQuery updates were done. Maybe something isn't working with the used Safari version anymore.

**Comment by henrikac** [comment]
@SenseException I noticed it on my machine at the office - I will check the version on monday. However, on my personal laptop it looks fine (`Safari Version 16.6 (18615.3.12.11.2)`)

**Comment by henrikac** [comment]
@SenseException the Safari version on my office computer is `Version 16.6 (18615.3.12.11.2)`. I had hoped the version was different because that *might* explain why.

**Comment by SenseException** [comment]
At least you did show that it shouldn't be a bug on the website if Safari of the same version have different results. Anything at work that blocks the JavaScript code I mentioned in the earlier comment? Does https://www.doctrine-project.org/frontend/js/bundle.js load when you open the website at work? Or maybe browser cache and something similar?

**Comment by henrikac** [comment]
@SenseException yeah, they are both loaded. Turned out to be a caching problem 🙈 The site looks as expected after the cache was cleared.
