### ISSUE TITLE
Project link on inactive projects broken

### ISSUE THREAD

**Issue by derrabus** [doctrine/doctrine-website#576]
The GitHub link on the banner displayed on the project page on inactive projects contains a template variable `{{ project.repositoryName }}` that is not expanded.

On https://www.doctrine-project.org/projects/annotations.html

![Bildschirmfoto 2024-04-03 um 16 35 01](https://github.com/doctrine/doctrine-website/assets/1506493/3e9285d9-2dca-449f-89fa-31889b87b2e1)

HTML source:

![Bildschirmfoto 2024-04-03 um 16 34 44](https://github.com/doctrine/doctrine-website/assets/1506493/246df4e3-15f3-44b7-9028-2d5813a5b64a)

**Comment by SenseException** [comment]
Thanks for reporting
