### ISSUE TITLE
Bullet lists are not rendered correctly

### ISSUE THREAD

**Issue by malarzm** [doctrine/doctrine-website#71]
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/annotations-reference.html#title.1.47

vs

http://doctrine-orm.readthedocs.io/projects/doctrine-mongodb-odm/en/1.2.x/reference/annotations-reference.html#referencemany

**Comment by jwage** [comment]
Something about the RST syntax is causing this.

**Comment by malarzm** [comment]
Seems like parser is not supporting:

```
-
    list item
```

correctly, I guess easiest will be to change our docs to supported format.
