### ISSUE TITLE
Broken links and API docs missing link to code

### ISSUE THREAD

**Issue by matuskopo** [doctrine/doctrine-website#89]
Hi,

I understand there was a need for new modern fresh responsive design, but from functionality scope it's not well done. As first, any previous existing URLs are not working now. Anything I've had in bookmarks, or if I'm using them from any discussions redirects to Not Found page :(

Second, when I've been using your previous API docs, I used to click on functions/properties to get into code and see, how the things are done. Now I'm not able to do it. Am I missing something?

Thank you
Bye

**Comment by Ocramius** [comment]
Could you please report the broken links? Most pages have correct redirects in place.

As for the API docs, they aren't there yet because current documentation generators are a bit clunky and we didn't throw time at them yet, since the grand majority of users have IDEs handling that bit.

**Comment by jwage** [comment]
I fixed an issue this morning in #90 with how we migrated our blog posts. Posts that had periods in the url did not get the url maintained properly so that one is fixed now. I am anxious to hear back from you on what URLs did not get maintained so that I can quickly address the problem. Thanks!

**Comment by jwage** [comment]
@matuskopo any chance you could help me out and let me know which links you are using that are not working?

**Comment by matuskopo** [comment]
Hi,

for example these links:
https://www.doctrine-project.org/api/orm/2.5/class-Doctrine.ORM.EntityRepository.html
https://www.doctrine-project.org/api/collections/1.3/class-Doctrine.Common.Collections.Criteria.html

should redirect here:
https://www.doctrine-project.org/api/orm/2.5/Doctrine/ORM/EntityRepository.html
https://www.doctrine-project.org/api/collections/latest/Doctrine/Common/Collections/Criteria.html

And second, if I'm checking matching method here: https://www.doctrine-project.org/api/orm/2.5/Doctrine/ORM/EntityRepository.html#method_matching
I'm not able just to click on for example "Collection" return type to see it's specification.

Thank you
Bye

**Comment by jwage** [comment]
Thanks. So it looks like it is all api docs links. We switched to Sami and they generate a different url structure. I will look in to trying to implement some kind of redirect.

**Comment by jwage** [comment]
API docs now link to github source code as of #145

**Comment by jwage** [comment]
I am unfortunately not going to be able to maintain the same URLs for the API docs. Since we switched to Sami and they don't support customizing the URLs, it is not easily possible. I apologize for the inconvenience.
