### ISSUE TITLE
Add doctrine-mapping.xsd to the new site

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#92]
It needs to be located here:

- http://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd
- https://www.doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd

Previously it looks like we had a redirect setup to this file in github: 

- https://raw.githubusercontent.com/doctrine/doctrine2/master/doctrine-mapping.xsd
- https://raw.githubusercontent.com/doctrine/mongodb-odm/master/doctrine-mongo-mapping.xsd

**Comment by jwage** [comment]
Fixed in bca2cd985edc55b0d52e9b879c1c88f499cd5410

**Comment by malarzm** [comment]
@jwage previously we also had a possibility to link to specific version of XSD, i.e. https://www.doctrine-project.org/schemas/odm/doctrine-mongo-mapping-1.0.0-BETA12.xsd (from our docs). Do we want to maintain the behaviour?

**Comment by jwage** [comment]
How did this work before?

**Comment by jwage** [comment]
Gotcha, I was trying to find where that rewrite rule is on the old server last night but I could not find it. @beberlei do you know?
